[project]
name = "django-fontawesome-5"
vesion = "1.1.0"
description = "FontAwesome integration form django projects"
authors = [
    { name = "Benjamin Frost", email = "info@btfrost.com" }
]
maintainers = [
    { name = "François GUÉRIN", email = "frague59@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "Django>=2.1"
]

[tool.setuptools.dynamic]
readme = { file = "README.md", content-type = "text/markdown; charset=UTF-8" }

